### PR TITLE
Add '-f' option to show full (last) slide of overlayed slides in the 'next' window

### PR DESCRIPTION
**Pull request by wupeka**

### CODE REVIEW

**Comment by AndreasBilke** [comment]
Could you explain in more detail what this pr should do? From the commit
messages I am not sure what this is about.

**Comment by wupeka** [comment]
W dniu 09.03.2016 o 09:28, Andreas Bilke pisze:
> Could you explain in more detail what this pr should do? From the commit
> messages I am not sure what this is about.
Hi
After pushing this change and pull-requesting it I realized that it
might not be well explained.

When presenting a presentation done in Beamer with overlays (eg. lists)
with current grouping settings (without -g) I get the current frame on
the left and the next 'first' frame on the right, so I don't know what
will appear next on the screen (it's only shown on small thumbnail below).
Without grouping enabled (with -g) I only see the next frame, and not
the full list that I'm currently going through
In '-f' mode on the right I see either last frame from the current list
(full), or if I'm presenting the last one - the next 'last frame'.
Try using the attached file in different settings (with/without -g,
with/without -f) to see the difference.

Witold Krecicki

**Comment by AndreasBilke** [comment]
I clearly see a usecase for this but I am currently not happy about the
"wording" of the feature. I have no better name for it but I think full
slide grouping does not explain what this flag actually does.

**Comment by wupeka** [comment]
A long description could maybe be "Show last slide of the current group instead of first slide of the next group in the 'next' window" but I don't know how to shorten it to be explanatory....

**Comment by diraimondo** [comment]
I think this should not be an option: it should the default if the grouping is enabled. IMHO

**Comment by AndreasBilke** [comment]
@wupeka sorry for taking so long. I would agree with @diraimondo . So this should be the default behaviour. Could you change your PR so that your feature is always used? So this shouldn't be an option anymore.

**Comment by phillipberndt** [comment]
This change is currently based on changing the user-slide definitions such that slide transitions occur one slide earlier than they actually do, i.e., when the full slide with all overlays shown is being displayed. I don't think that this is a good solution, because it disrupts the slide counter in the bottom right corner (which now displays one slide early). This should be fixed before merging this change.

([Here's what I've done locally as an alternative](https://github.com/phillipberndt/pdfpc/tree/fix-user-slide-display); this still is probably not the cleanest possible solution..)

**Comment by AndreasBilke** [comment]
I used the implementation of @phillipberndt and made it a default change.

**Pull request closed without merging**
