### PR TITLE
Swap j and k in pdfprcrc

### PR DESCRIPTION
**Pull request by kiryph**
User who are familiar with vim are used to 
j = `<Down>` arrow, i.e. next line
k = `<Up>` arrow, i.e. previous line

### CODE REVIEW

**Comment by AndreasBilke** [comment]
In June we already swapped it to the current configuration. I think we
cannot make happy all at once, so if someone likes other bindings they can
configure it in their own pdfpcrc file.

**Comment by kiryph** [comment]
Do you know why it was swapped? The commit 969b1672d557c67254b994102ceed482ffd7c6b5 does not contain any motivation.

The keybindings `j`/`k` are well-known for vi-style. Just to give a glimpse how wide-spread these are:
File Managers:
- vifm
- ranger
- ncdu - disk usage browser (ncurses)

File Viewers:
- **less**
- xzgv - Image viewer
- feh - Image viewer
- apvlv - PDF viewer
- pdftools - PDF viewer
- **zathura** - PDF viewer

Music Players:
- cmus - (ncurses)
- vimus - (ncurses)
- vimpc

Organizers:
- TuDu - To-do list manager
- calcurse - Organizer

Web Browsers:
- Firefox w/**vimperator** or pentadactyl or VimFx
- Chrome w/**Vimium** or cVim
- vimprobable - webkit-based browser
- dwb - webkit-based browser
- jumanji - webkit-based browser
- luakit - webkit-based browser
- uzbl - webkit-based browser
- xombrero - webkit-based browser
- vimb - webkit-based browser
- w3m - browser (text)
- qutebrowser - browser
- **lynx** - ncurses web browser

Mail Clients:
- notmuch - mail indexer
- sup - mail client (ncurses)
- **mutt** - mail client
- **Gmail**

Window Managers:
- i3wm (kinda)
- wmii
- howm

Shells / Terminals:
- tmux
- **Bash and zsh**
- **all apps using readline**

Misc clients:
- **tig** - Git interface (ncurses)
- weechat - IRC client (text)
- newsbeuter Feed reader (text)
- rtv Reddit terminal viewer

Office:
- viemu extension for Word, Outlook, SQL Server
- LibreOffice w/Vibreoffice
- Abiword
- **Evince**
- sc - spreadsheet (ncurses)
- sc-im - spreadsheet (improved version of previous)

Text editors / IDEs:
- vi clones: elvis, vis, pyvim, Yzis, kakoune, jVi, nvi, Stevie, vile, BusyBox vi
- bviplus - Hex editor
- Sublime Text Vintage Mode
- Atom Vim Mode Plus
- Visual Studio Code VsVim
- Emacs (**evil mode**)
- Kate vi mode

IDEs:
- Eclipse w/**vrapper**
- XCode w/Xvim or viemu
- IDEA, Rubymine w/**ideavim**
- Visual Studio w/viemu or vsvim

I do not know what you are using for coding, but I would suspect that if you would install a vim emulation, it would use `j` to go forwards and `k` to go backwards.

Any chance you would reconsider?

**Comment by AndreasBilke** [comment]
As I said, please configure your own pdfpcrc. You can just put these two
lines in the custom pdfpcrc and leave the default config (in system paths)
untouched.

**Comment by kiryph** [comment]
I can't follow you here: The commit in question does not refer to any issue someone raised. I can't see anybody with a different opinion. Also @phillipberndt who commited this has not said anything. And in case it is actually his preference, I would still disagree that it should be the default. It's the choice of a single developer and to require anybody else to change it back to the behavior in the rest of the world seems like a troll.

It is not about creating a personal pdfprc which I will do anyway because the presenter device I use triggers only arrow keybindings.

If no one follows common norms, everyone has to re-configure everything to get consistent behavior. I prefer to use default keybindings except I have good reason not to do so.

But I guess I have not convinced you anyway.

I also do not bother anymore because I can't get pdfpc work properly on macOS. Actually, I haven't found any gtk+3 GUI application which has been adapted properly to macOS from which one could figure out how to do this.

**Comment by phillipberndt** [comment]
[See this old PR for our motivation](https://github.com/pdfpc/pdfpc/pull/243#discussion_r120067324): While I was aware of the VIM bindings, the issue is that there's no obvious, indisputable way to map up/down to next/previous. Since "j" is left from "k" in all relevant keyboard layouts, and left maps more naturally to previous, we thought that having the mapping this way around would make more sense to people who aren't used to VIM's bindings.

However, I wasn't aware that Evince allowed to use these keys in presentation mode and uses them the other way around. @AndreasBilke To me, that *is* a strong reason for changing the mapping back.

> Actually, I haven't found any gtk+3 GUI application which has been adapted properly to macOS from which one could figure out how to do this.

That is because GTK itself doesn't properly support MacOS, and that is because MacOS has some pretty non-standard ideas about what applications should be allowed to do with the GUI and what not, especially for applications launched through a terminal rather than the launch services.

**Comment by fnevgeny** [comment]
@kiryph 
> Just to give a glimpse how wide-spread these are:

I wonder why you missed `Nethack` :)

**Comment by kiryph** [comment]
@fnevgeny fortunately, one person is entertained by watching a vim user struggling when j and k are swapped 😁.

**Pull request closed without merging**
