### PR TITLE
WIP: CI runs for libsoup v2 and v3

### PR DESCRIPTION
**Pull request by AndreasBilke**

### CODE REVIEW

**Comment by AndreasBilke** [comment]
@fnevgeny I did the matrix setup as you proposed. On ubuntu it works without any problems. On windows I get a compilation error for libsoup3.

Do you know if the matrix approach is wrong or if the libsoupv3 version on windows might have problems?

**Comment by fnevgeny** [comment]
On Ubuntu, *both* runs used libsoup-2.4, please see the logs. I'm surprised it worked (in the sense - the matrix build) for Windows. It's another "chicken and egg" problem - you try to apply a change to a CI action, but what should github do - run the CI from the master against the new version or first apply the patch and then run? I guess it works in a random way, kind of a race condition. Maybe there is a smart trick to do it reliably.

Back to the problem, it seems the two VAPI's (2.4 and 3.0) conflict. 2.4 is anyway included as a dependence of webkit2gtk-4.0. webkit2gtk-4.1 uses libsoup3. Still, the presence of both libsoup-2.4.vapi and libsoup-3.0.vapi in the standard Vala installation is a problem, IMO...

**Comment by fnevgeny** [comment]
> 2.4 is anyway included as a dependence of webkit2gtk-4.0.

Never mind. There is no webkit2gtk in the Windows build...

**Comment by fnevgeny** [comment]
I think https://github.com/pdfpc/pdfpc/pull/667/commits/d1ba29eb062ef3864fd6b215559b089d23d6722b is worth applying anyway.

**Pull request closed without merging**
