### PR TITLE
WIP: Build matrix for pdfpc features

### PR DESCRIPTION
**Pull request by AndreasBilke**

### CODE REVIEW

**Comment by AndreasBilke** [comment]
@fnevgeny I began to build a matrix pipeline to check against every combination of our features.

One question: I came across the libmarkdown dependencies which is needed for every build not only for mdview enabled ones. Do you know why?

**Comment by fnevgeny** [comment]
Well, libmarkdown converts MD to HTML, which should be enough for Web-based REST clients. So strictly speaking, libmarkdown should not be needed if (in addition to `-DMDVIEW=OFF`) REST is disabled, too.

**Comment by AndreasBilke** [comment]
Okay, I asked the other way around. For which features `libmarkdown` is needed? From your answer I assume its MDVIEW and REST, right?

**Comment by fnevgeny** [comment]
> Okay, I asked the other way around. For which features `libmarkdown` is needed? From your answer I assume its MDVIEW and REST, right?

Yes, that's right.

**Review by fnevgeny — APPROVED** [review]
I think it's OK now.

**Pull request merged**
