### PR TITLE
[movies-gstreamer] Use glimagesink instead of xvimagesink

### LINKED ISSUE #197: Videos playing sound but not images
I'm encountering an issue that puzzles me a little: presentations embedding video play the sound as expected, but no image.

It was previously working well, and stopped working without changing PDFPC version. This hints to a personal system environment issue, but I have investigated it carefully (cf below) without being able to isolate the culprit. Maybe someone might have an idea?

My configuration: Ubuntu 16.04, HiDPI laptop screen, gnome-shell, Intel HD5500 video card. The issue arise with the Ubuntu packaged version as well as with a fresh compilation from sources.

**What does not work:**
When the slides have videos, the sound starts playing as it should, but no image. Tested with several PDF, several video format, including the 'official' sample [video PDF](https://pdfpc.github.io/demo/pdfpc-video-example.zip). I get no warning/error on the command line (ie, no complains from `gstreamer`).

**What I've tested:**
- running the video directly with gstreamer (`gst-launch-1.0 filesrc location=<your video> ! decodebin ! autovideosink`): it works well (ie, the video is correctly played, both image and sound)
- creating a new user account (to make absolutely sure there is nothing dodgy in the environment) and starting `pdfpc` from there. Still doesn't work.
- tried in full-screen or windowed mode: no difference
- tried without grouping the overlays: no difference
- tried in a wayland session instead of X11: no differences with respect to the videos
- tried xfce instead of gnome-shell: no difference
- running `pdfpc` in a debugger does not help as everything works well from `pdfpc`'s perspective (ie, the video is handed over to `gstreamer` which starts playing it -- we hear the sound). Only the video does not appear.
- contrary to #224, compiling with `pdflatex`, `lualatex` or `xelatex` make no difference.

At that stage, my best guess is something goes wrong between `gstreamer`, `X11` and the Intel driver [except that it works if I call directly `gst-launch`). But I'm not sure how to investigate that. Any idea?

### PR DESCRIPTION
**Pull request by severin-lemaignan**
Closes #197

### CODE REVIEW

**Comment by phillipberndt** [comment]
The [GStreamer](https://gstreamer.freedesktop.org/documentation/plugins.html) homepage lists glimagesink as a ["bad" plugin](https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-bad-plugins/html/) while the ximagesink is among the "good" plugins. In fact, on my system, `glimagesink` is *not* installed. I agree that exchanging the gstreamer backend is a better workaround than disabling client decorations though (as that'll probably create new errors for other users).

* Is the `ximagesink` an alternative?
* There's `Gst.ElementFactory.find`, we could keep 'xvimagesink` as a fallback (and note somewhere that installing glimagesink might fix errors with video playback)

**Comment by severin-lemaignan** [comment]
For reference, a copy-paste of the suggestions by the gstreamer dev:
```
ndufresne:  skadge, one way is to disable client side decoration
                   the other way is to use gtk_widget_set_visual()
                   Which require listing the visual from the GdkScreen
                   and pick one that has no alpha
                   the third option is to fix xvimagesink, to properly query the parent window rather then hardcoding a visual
                   skadge, there is more option, you could use gtksink, gtkglsink
skadge       ok! Thanks a lot! I'll try first with nocsd, and if it solves the issue, I'll investigate set_visual
ndufresne   or glimagesink
skadge       Yep, I've played a little with gtksink, but it would involve quite a bit of change to pdfpc...
ndufresne    skadge, what you would gain, is that it's no longer X11 specific
skadge        Would be an option, I guess, but I'll try first the others :-)
ndufresne    skadge, maybe give glimagsink a try, that binds you to GL though * glimagesink this one at least is a drop-in replacement
```

**Comment by severin-lemaignan** [comment]
Regarding `glimagesink`:
```
__tim        skadge, we plan to move -gl to -base really soon
ndufresne    well, glimagesink itself not that much, but it's entirely based on libgstgl which is unstable indeed the API in this iteration has been cleaned up, and will probably land to -base soon skadge, if that reassure you and it's also the only sink for Android application, so we try to not mess-up with users on that
```

So it seems safe to use (even though right now it requires users to install `gstreamer-plugins-bad`).

**Comment by AndreasBilke** [comment]
So we would loose the opengl depencency shortly?

**Comment by severin-lemaignan** [comment]
@AndreasBilke as I understand, they plan to move `gliagesink` to `gst-plugin-base`, which would mean that gstreamer itself would then defacto depend on OpenGL.

**Comment by severin-lemaignan** [comment]
I'm fine adding `xvimagesink` as a fallback, but relying on `glimagesink` (ie OpenGL dep) is not much worst than relying on `xvimagesink` (X11 dep) -- if at some point we want to port to another platform (Windows, macOS, Android...), we will have to get rid of `xvimagesink` anyway.

**Comment by phillipberndt** [comment]
> ..but relying on glimagesink (ie OpenGL dep) is not much worst than relying on xvimagesink (X11 dep)

True. I'd even say that relying on OpenGL is the better choice in the long run. That's why I suggested to use xv as a fallback rather than having things the other way around. The point of the fallback is that if we don't have it, then merging this PR will break video playback for every existing user who hasn't got the -bad package installed. And it's likely that it'll break some packages as well, because who knows if package maintainers check the changelog for runtime dependencies..

**Comment by severin-lemaignan** [comment]
I've added a fallback on `xvimagesink` + a little bit of documentation.

**Pull request merged**
