### PR TITLE
Use GNUInstallDirs module for proper paths

### PR DESCRIPTION
**Pull request by fnevgeny**

### CODE REVIEW

**Comment by paulmenzel** [comment]
Does the `README.md` need to be updated now?

**Comment by fnevgeny** [comment]
In principle yes, but it also de-facto serves as docs for the released versions...

**Comment by AndreasBilke** [comment]
But it reflects the master state.

Am 11. April 2019 13:52:22 MESZ schrieb Evgeny Stambulchik <notifications@github.com>:
>In principle yes, but it also de-facto serves as docs for the released
>versions...

**Comment by fnevgeny** [comment]
OK :).

**Pull request merged**
