### PR TITLE
added option to configure the size of the presenter window

### PR DESCRIPTION
**Pull request by leesaudan2**
as titled

### CODE REVIEW

**Comment by fnevgeny** [comment]
OK, let's think a bit more generally:
- Do we need this because the default windowed mode has an inconvenient size (half of the full screen in each dimension) or there is a real need to adjust it from run to run? In the first case, it is probably better to set via the pdfpcrc file.
- Do we still need the `-Z` option at all? Once upon a time, it was used as a workaround for placing the presentation window against the will of some window managers, I believe. But now we are hopefully doing much better.

**Comment by leesaudan2** [comment]
Well... please at least keep it configurable via pdfpcrc.  The command line option would be handy in some cases.  Below is why I made this patch.

I have been using an older version of pdfpc (version 4.3.4, which is found in Debian's package repository).  When I run it in windowed mode (for video conferencing with Zoom), the two windows do not allow resizing (why?) from the window manager.  Fortunately, I found the -Z option, which allowed me to specify the size of presentation window.  But I'm still frustrated that there is no parallel for customizing the size of the presenter window (why?).  So, I checked out the source code and added this missing option.

Of course, when I did this, I checked out from the "master" branch.  Not until I tested my patch did I realized that this version (and versions since #173, 8790eac5bb4534893ba137b83007ab511ca4d061) actually allows me to resize both windows dynamically from the WM.  Then, I realized that my patch is not as need as it once was.  But anyway, since the patch has already been written, why not share it with others?

**Comment by fnevgeny** [comment]
So maybe just make `-Z` operate on _any_ non-fullscreen window (be it either presenter or presentation, or both, depending on the `-w` option)?

**Comment by leesaudan2** [comment]
> So maybe just make `-Z` operate on _any_ non-fullscreen window (be it either presenter or presentation, or both, depending on the `-w` option)?

Not a good idea.  Very often, the presenter's monitor (e.g. a notebook, lower resolution) and the presentation monitor (e.g. a big flat panel TV, very high resolution) are of different resolutions.  They're often of different aspect ratios, too.  So, you would want the two windows to have different sizes.  One size does not fit all.

**Comment by fnevgeny** [comment]
>  So, you would want the two windows to have different sizes.

Why/when? With the `-w both` option (mostly intended as demo or debugging tool), they appear on the _same_ screen. So no issue of different aspect ratios etc.

**Comment by leesaudan2** [comment]
> > So, you would want the two windows to have different sizes.
> 
> Why/when? With the `-w both` option (mostly intended as demo or debugging tool), they appear on the _same_ screen. So no issue of different aspect ratios etc.

It's easy to move the windows to two separate monitors.  Most window managers can handle that.

**Comment by fnevgeny** [comment]
> It's easy to move the windows to two separate monitors.

And it's similarly easy, if not easier, to _resize_ a window. Why would you want to move a window between two monitors in the first place, BTW?

**Comment by leesaudan2** [comment]
> > It's easy to move the windows to two separate monitors.
> 
> And it's similarly easy, if not easier, to _resize_ a window. Why would you want to move a window between two monitors in the first place, BTW?

A command line option would make it possible to automate the window-sizing task from shell scripts.  This is easier and faster than having to grab the mouse and click every time.

You never move windows between monitors?  Why not?

**Comment by fnevgeny** [comment]
> A command line option would make it possible to automate the window-sizing task from shell scripts.

Give me a single specific example, with a justification.

> You never move windows between monitors?

pdfpc windows? Never.

> Why not?

Because they are placed automatically. Why do *you* need to?

**Comment by leesaudan2** [comment]
> > A command line option would make it possible to automate the window-sizing task from shell scripts.
> 
> Give me a single specific example, with a justification.

$ pdfpc -A 1280:900 -Z 1024:576 slides.pdf &

I use this when teleconferencing with colleague using https://zoom.us/

Main monitor: 1280x1024.  The presenter window can fit, leaving ~100 px at top+bottom for system tray and Zoom's control bar.  Presentation window: shared to other Zoom participants, moved to beyond the right of main monitor (yes, making it not visible to me, but still "mapped" (X11's terminology), so that Zoom can grab it's contents and show it to my colleagues).

I don't need to see the presentation window.  I can see the contents and laser point in the presenter window.  Zoom will send the contents of the slides to the others.


> Because they are placed automatically. Why do _you_ need to?

As mentioned above.

Sometimes, it is useful to have the presentation shown in a window, not fullscreen, so that we can show other stuff side by side.  e.g. interactive viewers of 3D models.

Sometimes, your slides are 16:9 but the presentation monitor is 4:3 (or 5:4 or others) or vice versa, and --- while keeping the aspect ratio of the slides --- you want to use the otherwise wasted screen space to show other stuff.

There are so many possibilities.

**Comment by fnevgeny** [comment]
> Presentation window: shared to other Zoom participants, moved to beyond the right of main monitor (yes, making it not visible to me, but still "mapped" (X11's terminology)

Hmm, just to understand: you don't really have a dual-*monitor* setup, correct?

**Comment by leesaudan2** [comment]
> > Presentation window: shared to other Zoom participants, moved to beyond the right of main monitor (yes, making it not visible to me, but still "mapped" (X11's terminology)
> 
> Hmm, just to understand: you don't really have a dual-_monitor_ setup, correct?

For this particular use-case, NO.

But I also use pdfpc in other situations where I *do* use dual display.  E.g. presentation in a conference room, with a projector attached to my laptop via a VGA cable.  Even in that case, windowed mode would be useful, e.g. the projector settings may be optimized for a 4:3 screen, while my slides are prepared with a 16:9 aspect ratio.  With windowed mode, I can fit my 16:9 slides to the full projector screen width, leaving space above/below the slide to show other things.

**Comment by AndreasBilke** [comment]
Sorry I can't give constructive feedback to this issue. I also do not see a real use case for that therefor I hand over the decision to @fnevgeny .

**Comment by fnevgeny** [comment]
I'll return to it in a few days, too busy now...

**Comment by wichmannpas** [comment]
I appreciate this PR too, it comes in very handy when giving presentations over a shared screen. When using the `-Z` option as given in master, the presenter window is very small independent of the parameters.

**Comment by fnevgeny** [comment]
Well, if non-manual window placing is important, it should also include the offsets, not just the dimensions. Then, it might make sense to use the standard notation of `WxH[+X+Y]` instead of `W:H` (and respect `+X+Y` if present, of course).

**Comment by b10n** [comment]
This feature would be helpful to me too. However, I think making the presenter window resizable is a more straightforward solution.

**Comment by b10n** [comment]
> > This feature would be helpful to me too. However, I think making the presenter window resizable is a more straightforward solution.
> 
> The presenter window _is_ resizable.

Sorry, I missed that. Please ignore my comment.

**Comment by jgmbenoit** [comment]
I am looking for something like that when I present via Zoom.
Combining the `-Z <SomeWidth>:<SomeHeight>` and `-w both` works.
However setting the Width and the Height depends on the resolution of the screen while what really matters is the ratio. Is there  room to add a new momenclature to the `-Z` option so that the ratio can be set and the size deduced. The standard notations  aforementioned by  @fnevgeny can be used: `<SomeWidth>x<SomeHeight>` for exact dimension, and `<H>:<W>` for ratio. However standard, this change may cause backward compatibility.  Along this line, a new `-Z` argument may indicate that we actually  want to deduce the ratio from the PDF itself. This can be a default behaviour when `-w both`  is used.  I am also wondering if the `pdffitwindow` option from hypref can be honoured.

**Comment by fnevgeny** [comment]
> and `<H>:<W>` for ratio.

But what about the *actual* size? I guess you want some specific size for sharing the window via `zoom`.

> I am also wondering if the `pdffitwindow` option from hypref can be honoured.

In a sense, this is what pdfpc is *always* doing - there are no window scrollbars :). But the question remains: what absolute dimensions should be assumed?

**Comment by ceriottm** [comment]
I also find that the `-w` mode is great for giving presentations using zoom, and being able to set the size of the two windows would make this even more useful.

**Comment by stefanct** [comment]
`-Z` is very useful for screencasts because one can easily overlay other windows (e.g., a webcam), which is not (easily) possible in full-screen mode. My current version does not even support resizing the presenter window which makes it rather hard to read anything. But even then I would rather preset the size in my makefile...

**Comment by mgkuhn** [comment]
> * Do we still need the `-Z` option at all?

@fnevgeny Yes, I do! It is very important to me that I have full and exact control over the presentation window size *in pixels* from the command-line, which is what option `-Z` provides.

I'm using pdfpc to prepare screencasts with OBS Studio, and I need the presentation window to have exactly the same width and height in pixels as the production format of the MP4 file that I produce (e.g. 960 x 720 px), such that there is later no rescaling of the rendered PDF page going on inside OBS. Rescaling of already rendered hinted PDF fonts makes them more blurry and destroys all the careful effort that went into hinting, anti-aliasing and subpixel rendering of the fonts shown.

The main reasons I am using pdfpc are:
* It gives me simple and precise control over the presentation window size (with option `-Z`)
* It gives me a plain presentation window that I can capture directly into OBS without first having to crop away other GUI elements, because the PDF page fills the window complete and to the exact pixel dimensions I requested.

I don't know any other PDF viewer that can do that. Please don't remove option `-Z` / `--size`.

**Comment by mgkuhn** [comment]
Rather than adding your own `width:height` parser, could you not use for both the existing `--size` and the proposed `--presenter-size` option the standard Xlib library functions [`XParseGeometry`](https://linux.die.net/man/3/xparsegeometry) and `XWMGeometry` (see #627), which provide a well-established standard syntax (more than 30 years old?) for specifying not just the size of X11 windows, but optionally also their position?

**Comment by fnevgeny** [comment]
> Rather than adding your own `width:height` parser, could you not use for both the existing `--size` and the proposed `--presenter-size` option the standard Xlib library functions [`XParseGeometry`](https://linux.die.net/man/3/xparsegeometry) and `XWMGeometry` (see #627), which provide a well-established standard syntax (more than 30 years old?) for specifying not just the size of X11 windows, but optionally also their position?

That's what [I already suggested](https://github.com/pdfpc/pdfpc/pull/507#issuecomment-626178000).

**Comment by ronoaldo** [comment]
Long time but I just discovered the tool now, and need exactly the same functionality. I went with a ultra-wide setup instead of a dual monitor one, and mostly I share windows/tabs when remote teaching. Right now it is a small inconvenience that the presenter screen is quite big and the --size/-Z option currently don't apply to both.

Is it OK if I try to make the suggestions implemented to move forward?

**Comment by fnevgeny** [comment]
@ronoaldo Sorry, I somehow missed your comment. Sure, why not.

**Comment by fnevgeny** [comment]
Superseded by #646.

**Pull request closed without merging**
