### PR TITLE
Externalize style sheet

### PR DESCRIPTION
**Pull request by AndreasBilke**
This is a preparation for #37 .

### CODE REVIEW

**Comment by rschroll** [comment]
Two concerns:

1) Will this CSS file get installed?  I don't see any cmake rules that would do that offhand, but maybe I'm not reading them correctly.

2) Is this the right approach?  We could read additional CSS rules from a user's config file that get applied over top of hardcoded rules in the code.  What's the advantage of a separate file for the default rules?

**Comment by AndreasBilke** [comment]
1) You are right, I forgot to add a install rule. I forced pushed the correction
2) A user who is interessted in own stylings can now change colors etc. I might modify the system-wide css or use file for a per-user styling.

**Comment by rschroll** [comment]
I can definitely see the use of a per-user CSS file.  But that should 
be loaded over top of the existing styles, and I don't really see the 
point in loading those initial styles via a system-wide config file 
rather than just hard-coding them.  (Of course, we might say the same 
about the keybindings, and I don't understand why we do things that way 
their either.)

But I haven't thought about this much.  If you think this is the right 
way to go, go ahead and merge it.

**Comment by AndreasBilke** [comment]
I would wait for the merge until we have our first release. Maybe we should
not put to push new things into the first one.

**Comment by rschroll** [comment]
Actually, I think a user CSS file would be a great thing to have in 
this release.  It'd show off the power of GTK3.

Now that I've thought about this, I think the separate system CSS file 
is the way to go.  It will give users some guidance as to what they can 
put in their user CSS file.

If you're happy with the setup here, I'd say go ahead and hit the merge 
button!

**Comment by AndreasBilke** [comment]
Some corrections. Now a user-specific css file is also loaded. Could someone give his last approval?

**Comment by rschroll** [comment]
Unfortunately, using a user CSS file causes all the system CSS rules to 
be ignored.  This seems to be by design: "Loads the data contained in 
path into this, making it clear any previously loaded information."

I think we need to create a second CssProvider for the user styles.  
This one can be added with priority Gtk.STYLE_PROVIDER_PRIORITY_USER, 
to make sure it overrules the system CSS file.

**Comment by AndreasBilke** [comment]
Okay, now the user file is loaded with a higher priority. Is this a documentation worthy feature?

**Comment by rschroll** [comment]
Yes, it's worth documenting!  It looks like you've gone ahead with that 
already.

My only quibble is with putting a CSS file in a directory named 
pixmaps, which seems a bit odd.  I think CONF_PATH was a perfectly fine 
place for it, but I don't feel strongly either way.  I'll let you merge 
it into master, in case you feel like rebasing away anything.  But the 
history looks pretty clean (aside from a spurious merge), so just hit 
the button if you'd like.

**Pull request merged**
