### PR TITLE
Fix rendering with notes. #416

### PR DESCRIPTION
**Pull request by AndreasBilke**
@fnevgeny Could you double check if #336 is still working?

### CODE REVIEW

**Comment by fnevgeny** [comment]
> @fnevgeny Could you double check if #336 is still working?

Do you think it would be better just to disable the "overall" whole-document page dimension calculations if --notes are provided? --notes means the user is using beamer, and there is no chance the page dimensions would vary.

In general, I dislike the beamer notes support - it's a hack to support a hack in the first place (I mean in beamer, artificially widening the slides to accommodate two screens)...

**Comment by AndreasBilke** [comment]
> > @fnevgeny Could you double check if #336 is still working?
> 
> Do you think it would be better just to disable the "overall" whole-document page dimension calculations if --notes are provided? --notes means the user is using beamer, and there is no chance the page dimensions would vary.

I don't know other software producing such slides, but I can't exclude it. pdfpc was more or less always producer agnostic designed and I think we should not introduce more assumptions.

> In general, I dislike the beamer notes support - it's a hack to support a hack in the first place (I mean in beamer, artificially widening the slides to accommodate two screens)...

It is :) But it is used.

**Comment by fnevgeny** [comment]
I'll check later tonight or tomorrow. Now finishing a proposal for tomorrow's deadline...

**Comment by fnevgeny** [comment]
> @fnevgeny Could you double check if #336 is still working?

Nope... See a test file attached.
[t.pdf](https://github.com/pdfpc/pdfpc/files/2753585/t.pdf)

```tex
\documentclass{article}

\usepackage[paper=A4,pagesize]{typearea}

\usepackage{xcolor}
\usepackage{showframe}

\begin{document}

\pagecolor{yellow}
\centering Normal page (A4)

\clearpage
\KOMAoptions{paper=letter,pagesize}
\recalctypearea

\pagecolor{green}
\centering US Letter page

\clearpage
\KOMAoptions{paper=A6,paper=landscape,pagesize}
\recalctypearea

\pagecolor{blue}
\color{white}
\centering A6 page, landscape

\end{document}
```

**Comment by AndreasBilke** [comment]
@fnevgeny  i updated the code.

**Pull request merged**
