### PR TITLE
Update copyright statement and version number

### PR DESCRIPTION
**Pull request by AndreasBilke**

### CODE REVIEW

**Comment by rschroll** [comment]
I've never liked this unconditional output of the version number and 
the copyright statement.  How would people feel about adding a proper 
version option and getting rid of this thing?

(Sorry for changing the subject, but I forgot about this until now.)

**Comment by AndreasBilke** [comment]
What do you mean by "proper version option"? An command line option "--version" and "--copyright" to do this stuff? I would prefer this also.

**Comment by AndreasBilke** [comment]
I added an --version option.

**Comment by rschroll** [comment]
Looks good!

I'm going to merge this into the branch of #52, since this updates the 
version number.  Then it can land when we hit the big shiny 4.0 button.

**Comment by rschroll** [comment]
This is in #52 now.

**Pull request closed without merging**
