### PR TITLE
Move some command line options to config file

### PR DESCRIPTION
**Pull request by AndreasBilke**
Tackle #103

### CODE REVIEW

**Comment by AndreasBilke** [comment]
Could someone test this?

**Comment by AndreasBilke** [comment]
Do we want this feature in pdfpc? If yes, I would make this pr mergable.

**Comment by andybarry** [comment]
I think it's still worthwhile, but I don't think we should remove the ````--switch-screens```` option.  Often you'll show up at a place and need to get the presentation working fast and sometimes you want to switch screens for whatever reason.  It's good to have fast one-off access to that option.

**Comment by AndreasBilke** [comment]
I re-added switch-screens.

If you feel comfortable with this pull request, could you merge it?

**Comment by andybarry** [comment]
OK I merged it with one small additional change in 61aa1210 which makes sure that regardless of the status of the config file flag for switch screens, the command line option will switch them.  In other words, if both are true, the result is false.  I think this is more intuitive, since otherwise the user could set the global option, forget, and then the ````-s```` flag would do nothing.

**Pull request merged**
