### PR TITLE
Allow complete ungrouping of overlays to be saved

### PR DESCRIPTION
**Pull request by endzone**
This would fix one part of issue #108 and allow for a workaround on issues #102 and #109.

### CODE REVIEW

**Comment by AndreasBilke** [comment]
I would prefer a real option to disable grouping instead of putting work in
a workaround.

**Comment by rschroll** [comment]
This seems like a necessary step anyway.  We'll have to preserve the 
empty skip group in the pdfpc file once that real option sets it.  
(Unless we have another marker to indicate the skip group should be 
ignored and no slides are parts of overviews.  But that seems 
needlessly complicated.)  Why not put this in now, to let the 
workaround work, and then add the real option later?

I'm not convinced that the user_view_indices.length <= page_count check 
is necessary.  Naively, I wouldn't think that it could get longer.  And 
if it did, why is disabling the skip tag the right thing to do?  Of 
course, I also don't understand why the strict less-than check was in 
there before, so maybe I'm missing something.

**Comment by andybarry** [comment]
Is this still relevant now that we have the ````-g```` option?  It's clearly a minor change so if it's a bugfix I'm happy to merge it in regardless.

**Comment by AndreasBilke** [comment]
@endzone do you think this pr is still necessary?

**Comment by AndreasBilke** [comment]
The `this.user_view_indexes.length == this.page_count` case can only occur if every slide is in user_view_indexes, right? So it should be save to merge this pr.

**Pull request merged**
