### PR TITLE
Window resize

### PR DESCRIPTION
**Pull request by fnevgeny**
This patch set makes the windows (presenter and presentation alike) resizable. Also, added the `windowed` action (bound to `w` by default) to switch between the fullscreen and windows modes of the presenter window (should it be renamed to a more verbose `toggle_windowed_mode`, for example?

RFC:

- I am not sure whether a similar action should be present for the _presentation_ window; personally, I see no reason one would ever need it.
- There should, however, be a possibility (I might even consider it a good default) to start the presenter windowed (and the presentation window fullscreen - when the second monitor is available, of course). But the option to start both windowed should remain as well (for developers, if not anything else :)). Any suggestion for command-line/config option(s)?
- The resizing of the videos (when there are any on the current page) doesn't work correctly. I'd be ashamed to admit how many hours I've spent trying to find the reason, but all in vain... Perhaps somebody will be able to fix it. I have a gut feeling it might be related to the video issues on non-X platforms...

### CODE REVIEW

**Comment by AndreasBilke** [comment]
> RFC:
> 
>     * I am not sure whether a similar action should be present for the _presentation_ window; personally, I see no reason one would ever need it.

Me neither. But this only reflects my style of presenting.

>     * There should, however, be a possibility (I might even consider it a good default) to start the presenter windowed (and the presentation window fullscreen - when the second monitor is available, of course). But the option to start both windowed should remain as well (for developers, if not anything else :)). Any suggestion for command-line/config option(s)?

It should be a config file option (this sounds like a very static decision to me). But it should't defaulting to windowed. But I am very uninspired at names.

>     * The resizing of the videos (when there are any on the current page) doesn't work correctly. I'd be ashamed to admit how many hours I've spent trying to find the reason, but all in vain... Perhaps somebody will be able to fix it. I have a gut feeling it might be related to the video issues on non-X platforms...

I didn't tested it: But has the video at the presenter screen the wrong size or is there a quality issue? In any case, I wouldn't see this as a merge blocker. The occasions where this hits you might be rare.

**Comment by fnevgeny** [comment]
> So the only real problem is the ugly border stuff.

Hmm, did you run with the `-N` flag?

**Comment by fnevgeny** [comment]
> has the video at the presenter screen the wrong size or is there a quality issue?

The wrong size (and position). It's something weird. Basically, when one does n times resizing, the size of the video is that would be good for the (n-1)th window size. So if you resize the window and then resize it again by a minimal amount (a few pixels) it would be mostly OK.

> In any case, I wouldn't see this as a merge blocker.

Yes, but what really bothers me is _why_ it doesn't work (or rather why it works this strange way). Something must be wrong...

**Comment by fnevgeny** [comment]
> `w` does not nothing at i3.

Works fine for me both ways, just checked. Interesting... I'm on Ubuntu-18.10 (i3 version 4.15).

**Comment by AndreasBilke** [comment]
> Hmm, did you run with the `-N` flag?

With -N it is fine.

**Comment by AndreasBilke** [comment]
> Works fine for me both ways, just checked. Interesting... I'm on Ubuntu-18.10 (i3 version 4.15).

Okay, `-N` does the trick :)

**Comment by fnevgeny** [comment]
> But I am very uninspired at names.

What about changing the `-w` flag from boolean to accepting an option `[none|presenter|presentation|both]`? This breaks the backward compatibility, but ensures drawing attention to the new functionality :).

**Comment by AndreasBilke** [comment]
> What about changing the `-w` flag from boolean to accepting an option
> `[none|presenter|presentation|both]`? This breaks the backward
> compatibility, but ensures drawing attention to the new functionality :).

Sorry for the late response, but: Yes, good idea!

**Comment by fnevgeny** [comment]
> Sorry for the late response, but: Yes, good idea!

OK, I'll do it soon.

**Pull request merged**
