### PR TITLE
Run CI for every pull request

### PR DESCRIPTION
**Pull request by AndreasBilke**
Run the CI job for every PR to check the build before we merge.

### CODE REVIEW

**Comment by AndreasBilke** [comment]
@fnevgeny As we have now a Windows-build running, are you planning to release a downloadable setup file for windows platforms?

**Comment by fnevgeny** [comment]
> @fnevgeny As we have now a Windows-build running, are you planning to release a downloadable setup file for windows platforms?

No. I'm not really interested in Windows build as such; it was an exercise to ensure pdfpc is as OS agnostic as possible. The relevant changes have, in fact, been committed long ago, e.g., b2899e70919d870a7cf0813d0ca8197d3e5b4dd2 .

Also, making a standalone (i.e., not assuming MSYS2/MinGW is present) MSI installer is a huge PITA. It would be the last thing I want to spend my free time on :). On the other hand, an MSYS2/MinGW pacman package should be a trivial thing to do, so hopefully, somebody interested will take care of it.

**Comment by fnevgeny** [comment]
Hmm, is "**" really needed? Say, this very PR already has the "All checks have passed" notice.

**Comment by AndreasBilke** [comment]
You are right. I thought this is needed to check any PR branch and not just if it already landed in master. (I checked with an toy-PR)

**Pull request closed without merging**
