### PR TITLE
Added area highlighting and pointing.

### PR DESCRIPTION
**Pull request by br0xpl**
I found a need for highlight and pointing functionality from the presenter screen. 

There was a similar request here:
https://github.com/davvil/pdfpc/issues/40

### CODE REVIEW

**Comment by AndreasBilke** [comment]
Nice feature, but I found some problems with the pointer. I can move the mouse (with pointer on) nicely on the presenter view, but the pointer is not correctly mapped to the presentation on the second screen. (see the screenshot for one example).
If I am on the leftmost position with the pointer, the pointer is shown within the black area on the presentation view. So I think the position of the pointer must be shifted to the right (with the amount of black-ness on the sides).
pdfpc-pointer-feature

**Comment by br0xpl** [comment]
Hey Andreas,
Indeed - a silly typo in one line. Fixed in the latest commit. Try it out.

**Comment by AndreasBilke** [comment]
Okay, now it works for me.

Could you use spaces instead of tabs (you mixed tabs with spaces in the code)?

If some other maintainer agrree with your pull request, I am happy to merge
this.

**Comment by br0xpl** [comment]
Okay great! I've Fixed the tabs in 14ea27a - sorry for that..

**Comment by andybarry** [comment]
I'm pumped to try this soon -- traveling now so I don't have a dual monitor setup.  Will report back when I've fired it up!

**Comment by AndreasBilke** [comment]
@andybarry did you found some time to test this?

**Comment by andybarry** [comment]
Thanks for the ping, I'll try to do it tonight.

**Comment by andybarry** [comment]
OK, this is totally awesome.  Great job with the idea and the implementation!

Two things for me before we're ready for prime time:

1. When in "switched" view, (passing the ````-s```` flag), the pointer is stuck to the top left no matter what for me.  Hopefully an easy fix?

2. We should add some documentation for this.  Can you add a short description of how to use it to the man page: https://github.com/pdfpc/pdfpc/blob/master/man/pdfpc.in ?


Sorry it took me so long to take a look.  I just started a new job :)

**Comment by br0xpl** [comment]
Hi Andy, 
Thanks!
I cannot reproduce this problem in switched mode (-s). Could you please make a screenshot of both screens? 
So do you move the cursor on the presenter screen? Or you move it in the single slide (presentation) screen? Currently it works only by moving the red dot on the presenter screen.

Regards,
br0x

**Comment by AndreasBilke** [comment]
I also can't reproduce this. If the cursor is on the correct screen (the presenter) everything works.

**Comment by AndreasBilke** [comment]
@br0xpl could you add this feature to the man page in the meantime?

**Comment by br0xpl** [comment]
@AndreasBilke - done - sorry for the delay.

**Comment by AndreasBilke** [comment]
@andybarry ping :)

**Comment by andybarry** [comment]
New job has me completely swamped.  You guys should merge this and I'll file a bug and assign myself if I can reproduce the problem (was also experiencing #149 so might be related).

**Comment by alromh87** [comment]
I supposed this feature to be found at master but I could not find it at latest release.
It would be great if it could be merged?

**Comment by AndreasBilke** [comment]
This feature was released with v4.0.3 (in october 2016).

**Comment by AndreasBilke** [comment]
Please do not update your posts. I don't get the updates via the e-mail interface.

**Comment by br0xpl** [comment]
> when using only one screen and the -s switch

Hey alromh87, 
The pointer is supposed to work when you move to cursor on the presenter screen and not the main screen. On main screen you may move the standard mouse pointer. 

If you really wish to have the red cursor and highlighting working in single main screen - it should be pretty strightforward to implement/extend it though.

regards,
Blazej

**Pull request merged**
