### PR TITLE
WIP -- Renderers and cache

### PR DESCRIPTION
**Pull request by rschroll**
This is a work in progress.  I'm looking for some feedback before polishing up any parts that we actually want.  There are several different pieces muddled together here.

I started looking at the rendering system we have, and I noticed that we have one renderer per view.  This means that we may have five renderers rendering the same pages, which struck me as rather inefficient.  I wondered if it would be better to render the PDF once at a high resolution, and then downsample it for the various views (#19).

I divorced the renderers from the views, so now there's only one or two renderers, depending on if there are notes slides.  To see what this gets us, I compared the prerendering times for a ~60 page presentation I have.  This is not a perfect test, since the prerenderer runs in idle time, so the time may depend on what else the computer is doing.  But when I repeated tests, I got pretty consistent results, so these aren't entirely meaningless.  In windowed mode, the old code took an average of 10.3s to prerender, while the new code took 10.5s to prerender.  Keep in mind, though, that the new code prerenders at full-screen size even in windowed mode.  In full-screen mode with two monitors, the old code took 24.0s, while the new code barely took a hit, coming in on average at 10.9s.  Do note that this is without a separate notes slide.  With notes, I would expect the new code to take twice as long and the old code to remain about the same.

So, speed-wise, it's a bit of a wash.  My common use case (full-screen without notes) did improve significantly, but someone running with notes in windowed mode will see a significant slow down.  I feel like my use case is more common, so it's probably a win on average.  (Note that this test was done before the later commits that change how the overview rendering is done.)

With high-res renderings, we need a way to downsample them to the size of the views.  I originally assumed that Cairo would do this for us, but I discovered that it has long-standing problems when resampling to less than half the original image size.  Small features could disappear completely and gradients become very harsh.  (It's using an interpolation scheme that only looks at the nearest neighbors of a pixel for resampling.  This works fine for enlargements and modest shrinking, but once you go below half the original size, you start losing pixels altogether.)  One way around this would to blur the original image before resampling.  This did work, but all the codes I tried took way too long to be useful.

I did discover, though, that Gdk.Pixbufs built-in resampling does do a reasonably good and fast job at downsampling.  That's what's in the branch now.  It's not perfect -- there's a small but noticeable lag (probably a few hundred milliseconds) on page turns as the resampling occurs.  I'm testing on a rather beefy but bit old laptop; I'd be interested to hear how it performs on other hardware.

If we're doing the resampling with Pixbufs, we end up: rendering to an ImageSurface, converting to a Pixbuf to make a PNG, reading the PNG into a Pixbuf, painting the Pixbuf to an ImageSurface, converting that ImageSurface back to a Pixbuf, resampling the Pixbuf, and then rendering that Pixbuf onto the output Cairo surface.  This struck me as rather silly, so I converted the cache to save Pixbufs, not ImageSurfaces, cutting out many of this transformations.

If the only thing this work gave us was a questionable speed up, it probably wouldn't be worth it.  But I think this gives us significant flexibility in our layout.  Up to now, we've had to figure out the layout at the outset so we know how big the renderer should be.  But if we're resampling anyway, we can let the layout change.  I've allowed the windows to be resized.  (The presenter can't be shrunk from its initial size because of issues with the overview, but that should be solvable.)  I've also replaced the box-based layout with one based on Paneds.  When the mouse is over the handles, they'll turn white and you can drag to change to relative sizes of the various components.  This should be much easier to manage than trying to set up the layout through command line flags.  We could also imagine other features, like switching between fullscreen and windowed modes or swapping the presenter and presentation screens without restarting.

Since I was in the area, I messed with the prerendering system in the final few commits.  Now the overview will add icons as soon as the slide has been prerendered, which is nice.  It also happens to solve #15, but that's not really a reason to go with this approach -- we could solve it under the previous render model too.

I'm sorry that this is so much to take in all at once.  I didn't really understand the scope of this work until it was all underway.  I'm interested in hearing your reactions to the general ideas now.  Once we know which are worth keeping and which should be discarded, I can try to gather the ideas together a bit better and you can actually review what's changed a bit more easily.

### CODE REVIEW

**Comment by rschroll** [comment]
Of course, after doing all of this work, I finally went and checked the first things I should have looked at: Does the prerendering actually beat just-in-time rendering?  And the answer is, for the most part, no.

I timed how long it took to render to an individual view.  When rendering directly from the PDF, there's quite a bit of variation.  Most slides rendered in less than 10 ms each.  4-6 ms seemed quite common.  But some slides with detailed graphics could take 150 ms to render.  With this prerendering scheme, results are more consistent but generally worse.  Most slides take 20-30 ms to render.  Since there are, in general, at least three views to render at a time, this gets us up to the 100 ms / transition that I was feeling before.  Interestingly, the Pixbuf rescaling doesn't seem to be that important -- taking it out, I find render times in the 15-25 ms range.  The big delay is in the PNG decompression.  Storing uncompressed images, I get rendering times generally below 15 ms.  (Uncompressed and without rescaling, I get 2-8 ms times.  For the record, all of these are in windowed mode.)

I haven't tested the existing code yet.  The structure of the code is somewhat different -- instead of doing the rendering all at once, it is prepared first, and then actually drawn.  I'm sure the actual drawing is very fast, but since you still have to render on entering each page, I suspect the performance is similar.

Where does this leave us?  The one firm conclusion I've reached is that we should make it work without prerendering.  (Specifically, the overview.)  Perhaps that should be the default, and people can turn on the prerendering if they have a presentation where it's actually necessary.  (This would reduce the impact of #12, perhaps.)

Does this branch actually improve performance?  It will decrease time spent prerendering in some cases.  But not prerendering at all may be a better solution, and the added scaling for each pixbuf may cost us a frame or two each time we switch slides.

That said, I think we should consider this approach for the architecture changes it introduces.  Now that rendering is entirely held within the renderer, I think it will be easier to change the details and try out new schemes.  Perhaps a renderer that does mipmapping.  Perhaps one that proactively renders the next slide after it gives you the one you want.

Okay, enough babble from me.  What does everyone else think?

**Comment by andybarry** [comment]
I use detailed SVG-based graphics a lot, so perfect resolution + prerendering was a lot about what made pdfpc attractive to me.  Here we're still maintaining perfect resolution on the presentation end, so scaling the other views doesn't bother me very much.

Swapping the presenter and presentations screens without a restart is pretty exciting to me, but in this case, you'd lose the pixel-perfect render, which isn't good, especially since you'd end up with a confusing inconstancy between that and the command line flag.

The other thing I like about prerendering is that it makes every slide transition time the same.  When I'm giving a talk, I never want to be thinking, "did my slide remote flake out or is this next slide just complicated?"


The real question in my mind here is why aren't we faster now than before?  We're rending less images, so it seems like things ought to be better.  Does the scaling take a long time?  Maybe the other views were so low resolution that it didn't matter?

It's awesome that you worked through all this.  I'm excited to see the rendering pipeline improving!

**Comment by rschroll** [comment]
Right now, it renders the cache image at the resolution of the highest 
resolution screen.  So this means you get perfect resolution on the 
presentation if that is on the highest resolution screen.  Most 
projectors are not particularly high-res (there are still plenty of 
800x600 ones out there), so this is often not the case.

One way around this would be to render the cache image at the 
resolution of the presentation screen.  This would cause problems with 
a live screen swap, though.

For my sample presentation, it looks like, for most slides, the slowest 
bit was PNG decompression.  I haven't tested, but I suspect that the 
same holds for the compression.  If so, this suggests that rendering 
time will largely scale with the number of pixels being rendered.

Of course, all of this is with my presentation.  I use a blank 
background, lots of text and equations, and only simple SVG graphics. I 
notice that the PDF rendering slows down greatly for the few slides I 
had with more complicated graphics.  If you'd like to send me a few 
sample slides with your detailed graphics, I can run some timing tests 
on those and see how they compare.

After wondering how to tell if caching is worth it, I realized that we 
could just measure.  I'm about to add a commit that measures the 
rendering time during the prerendering and only caches the slide if it 
takes longer than some amount of time (15ms, right now).  This helps 
cap the amount of time a slide change can take, while not imposing a 
cache penalty if it's not really necessary.  Most of my slides render 
quickly enough not to need the cache.  I notice that the prerendering 
time is cut significantly, probably because we don't bother to encode 
as PNGs the slides we don't need to cache.

One problem with this is that there is a slight but noticeable 
difference between the cached and rendered slides, when there's 
rescaling done.  The rescaling gives a bit of fuzziness to the slides.

As part of this, I rejiggered the prerendering process to have it be 
driven, at first, by the overview (since the overview can no longer 
count on the images being available in the cache).  I thought this was 
going to greatly simplify things, but then I realized that this doesn't 
generate cache images for any overlay slides or notes slides, so we 
still have to do an explicit prerender looop after assembling the 
overview.

**Comment by rschroll** [comment]
I've written a test program to exercise the various operations that we 
do in the process of rendering and caching the slides.  Find it here: 
https://gist.github.com/rschroll/71a9cc6feb322b671293.  I'd be very 
interested to hear the results from typical presentations for the rest 
of you.

The test program takes a PDF file as an argument and then runs some 
test for each page of the presentations and reports eight timing 
measures.  (All of them are wall clock time, so there's some variation 
based on how busy your system is.)  The first six represent operations 
that we currently use:

Render measures the time to render the PDF page to an ImageSurface.  
This should be roughly comparable to rendering directly to the screen.  
This shows the most variation for my slides.  Some take less than 5ms; 
others take nearly 200ms.

Pixbuf measures the time it takes to paint that ImageSurface to a 
Pixbuf.  Most take just about 30ms.  Occasionally, I get times of 
several hundred ms here, but I can't reproduce them.  Perhaps these 
represent times where the process got interrupted.

Save measures the time to save the Pixbuf to a buffer in PNG format.  
This is the dominant factor in prerendering, it appears.  Most take 
between 180 and 200 ms, though a few take a bit longer.

Load is the time to decompress the PNG back into a Pixbuf.  Generally 
it takes 20-40ms, though some take longer.

Scale measures the time it takes to rescale the Pixbuf down to half its 
original size.  This is very consistently 18-20ms.

Surface is the time to write a Pixbuf to an ImageSurface.  This is very 
consistently 15-16ms.

The conclusions I draw from this are:
(1) Prerendering time is dominated by PNG compression.  Indeed, if I 
turn compression off, prerendering time decreases significantly.
(2) We may improve responsiveness during prerendering by moving PNG 
compression into another thread.  Poppler is (was?) not thread-safe, so 
it required locking, which is a pain.  We might be able to leave the 
Poppler rendering in the main thread and only do compression in a 
worker thread.
(3) For quite a few of my slides, it takes longer to decompress, 
rescale, and render a bitmap than it does to just render the PDF 
directly.

I was flipping through the Cairo documentation looking for something 
else when I came across RecordingSurfaces.  These surfaces record the 
drawing operations and let you play them back to other surfaces.  I 
started to wonder what was the expensive part of rendering a 
complicated PDF slide: translating PDF drawing commands to Cairo 
drawing commands, or running the Cairo drawing commands on an 
ImageSurface.  The last two columns measure this.

Record measures the time to render the PDF page to a RecordingSurface.  
This has extreme variability from 1.5ms to 150ms.

Playback measure the time to paint a RecordingSurface to an 
ImageSurface.  This also has quite a bit of variability, from 3 to 
40ms.  It is largely correlated, unsurprisingly, with the previous time.

I do note that many times Record + Playback < Render.  I suspect that 
this is because Render gets the PDF page into the cache, so Record can 
access it more quickly.  But I don't expect that this fundamentally 
changes any of these results.

This makes me wonder if we should be caching RecordingSurfaces of all 
the slides and rendering those at appropriate sizes.  The playback time 
is short enough in my case to beat out any attempt to decompress and 
render a PNG.  I'm not sure what this would mean for memory usage -- 
I'll try to come up with a test for that.

I'm very interested to hear what these results look like for others' 
presentations.

**Comment by AndreasBilke** [comment]
I tested three presentations. I published the results here: https://pub.bilke.org/2015-03-03-lCPBW5tRCas/
- File 1: This is a LaTeX beamer presentation. The slides with significant higher render time are filled with some knitr+tikz plots. There are a lot of "things to draw"
- File 2: LaTeX beamer, nothing fancy. Just text on itemize environment
- File 3: A lecture talk of one of my colleagues. Made with MS Powerpoint, quite a lot of equations, slide 18-20 and 44-45 contain JPG images.

**Comment by rschroll** [comment]
Thanks!  What I see is:
1) You have a better computer than I do.
2) The relative times are about the same as what I've seen.
3) Complicated bitmap images take time to translate into Cairo (the 
Record phase); complicated vector images take time to rasterize (the 
Playback phase).

Results from other presentations would still be helpful.  And I'm happy 
to hear thoughts from everyone else, even if you're still trying to 
puzzle things out yourself.

**Comment by AndreasBilke** [comment]
I measured render times for another presentation: https://pub.bilke.org/2015-03-05-txLcL7sgHaI/render-times-4.txt

This presentation has many vector graphics, most of them are rather simple. The huge render times (> 200 ms) comes from data plots.

Do you have any suggestions how to measure memory consumption without looking at `top`?

**Comment by rschroll** [comment]
I sent this by email, but apparently it never showed up:

> Do you have any suggestions how to measure memory consumption without looking at top?

Yeah, I think the way to do it is with --enable-mem-profiler.  Unfortunately, that causes a crash for me: https://mail.gnome.org/archives/vala-list/2015-March/msg00003.html.  I'd be interested to hear if any of you can get it to work.

---

How are people feeling about this at the moment?  There are three currently-implemented solutions:
- Current pixel-perfect prerendering
- Prerender everything to large bitmap, scale down for display
- Measure prerendering times, only cache expensive slides (which get scaled down for display)

There are also a few other ideas we could try out:
- Caching RecordingSurfaces (generally will give better render times, but can't guarantee a max time)
- Prerender at presentation size, scale up or down as needed from there (but what if presentation size changes?)
- Cache (some? all?) bitmaps, but rerender for pixel-perfectness after displaying the bitmap (guaranteed response, though image may be initially degraded)
- Other ideas?  Please speak up.

**Comment by AndreasBilke** [comment]
I would prefer the cache based on RecordingSurfaces. They seems for me the most ellegant solution. You can render pixel perfect, resizing of windows is allowed, the time consumption seems okay.

Do you have any working code for RecordingSurfaces to test it as a whole for pdfpc? I could test some slides and look at the memory consumption.

**Comment by rschroll** [comment]
On Sun, Mar 22, 2015 at 7:10 AM, Andreas Bilke 
<notifications@github.com> wrote:
> I would prefer the cache based on RecordingSurfaces. They seems for 
> me the most ellegant solution. You can render pixel perfect, resizing 
> of windows is allowed, the time consumption seems okay.

I do like this approach.  The one downside I see is that we can't 
guarantee a particular response time, whereas we generally can with a 
bitmap storage system.  I think that's an acceptable trade-off for 
generally better performance, but @andybarry does make a strong case 
that having a fixed max time for a page turn is very reassuring to the 
user, even if it's inefficient in other ways.

I don't have a RecordingSurface solution put together, but I can 
probably whip one up pretty quickly.  One benefit of my refactoring is 
that all drawing requests go through the renderer, so we should be able 
to swap rendering systems more easily.

**Comment by rschroll** [comment]
I've put together a RecordingSurface cache in my recording-surface 
branch.

Unfortunately, it doesn't work.  Well, it functions, but we're not 
getting pretty rescaling.  Right now, the recording surface is large, 
and the smaller views are not well resampled.  If I make the recording 
surface smaller, the larger views are a bit fuzzy.

I'm not sure why this is, but I have three guesses:
1) The RecordingSurface is recording pixels, not drawing operations.  
(But, then it's not really any different than an ImageSurface.)
2) Poppler is drawing pixels, not vectors.
3) Poppler adjusts its vector drawing depending on the pixel size for 
nice results.

**Comment by AndreasBilke** [comment]
@rschroll is there any chance that you might work on this further or should I close this PR?

**Pull request closed without merging**
