### PR TITLE
Multimonitor

### PR DESCRIPTION
**Pull request by AndreasBilke**

### CODE REVIEW

**Comment by fnevgeny** [comment]
So the whole problem with Plasma boils down to running `do_fullscreen()` _before_ the mapping event and not on it as was the case before (currently commented out). However, there are indeed other VM's (e.g., fvwm) that want just that. Yet others (Gnome either with or without Wayland) work both ways.

What do we do? Try to autodetect WM idiosyncrasies somehow or add another config option? In fact, I just realized we can attempt fullscreening _twice_, assuming it doesn't break anything. Neither is an elegant solution...

**Comment by AndreasBilke** [comment]
@fnevgeny I can remember what we where at the double full screening some time ago and that (and maybe other things) resulted in the same problems for some WMs as now. Plus you had the flickering of the windows. So there was no solution for everybody.

I would argue that we support the main players (gnome and KDE) and users of niche WMs are/should be capable of handling it on there own. Like awesome WM and xmonad and i3 support the moving of windows based on the title of the window.

**Comment by fnevgeny** [comment]
> Do we really need this part at all?

Further, even in the fullscreen multimonitor mode, we use `get_default_screen()`; there appears to be _nothing_ in the non-deprecated API's to get handle of something but the default screen (and, if I understand correctly, all modern DE's/WM's assume a single virtual screen) - so the efforts to get `this.screen_to_use` in the windowed mode are meaningless as well.

**Comment by fnevgeny** [comment]
> I would argue that we support the main players (gnome and KDE) and users of niche WMs are/should be capable of handling it on there own.

I disagree to call my favorite fvwm a niche one :)

OK, so then a `pdfpcrc` option? People don't switch WM's every day, so it's probably better to set it once and forget instead of using a command-line switch each time.

**Pull request merged**
