### PR TITLE
Implement slide transitions

### PR DESCRIPTION
**Pull request by fnevgeny**

### CODE REVIEW

**Comment by fnevgeny** [comment]
> Wow! Nothing to complain :)
> Would it be (easily) possible to have a global transition information? Like 'push every slide to the left'?

I thought we would stay away from populist options :). The beamer guide warns against using transitions excessively. BTW, it wasn't clear to me why the "fly" transition is not implemented in beamer.

It actually raises some questions: what should be done if only few slides in the document have transitions: use the "global" one only on the rest of the pages or override all? Or allow both variants?

**Comment by AndreasBilke** [comment]
> I thought we would stay away from populist options :). The beamer guide warns against using transitions excessively. 

You can't prevent people from doing silly things ;) But I could imaging that a global transition setting would be a next feature request

> It actually raises some questions: what should be done if only few slides in the document have transitions: use the "global" one only on the rest of the pages or override all? Or allow both variants?

If you have a global setting but also a per-slide setting, the slide setting should win. This would be the most consistent behavior for me.

*But*: If a global solution is too much pain in the code base, then forget about my point!

**Comment by fnevgeny** [comment]
OK. No, it should be rather easy to implement. It shouldn't be a global (pdfpcrc) option though, I guess.

**Comment by fnevgeny** [comment]
OK, it's in #500.

**Pull request merged**
