### PR TITLE
Shortcut to jump to the last overlay

### PR DESCRIPTION
**Pull request by AndreasBilke**
See issue #135 .

### CODE REVIEW

**Comment by AndreasBilke** [comment]
I tried to simplify the current code for jumping etc. Could someone double check the changes?

**Comment by AndreasBilke** [comment]
@andybarry could you double check the code?

**Comment by andybarry** [comment]
I'm traveling this week but will do it when I'm back next week.  Shoot me
another reminder if I don't.

**Comment by AndreasBilke** [comment]
@andybarry ping ;)

**Comment by andybarry** [comment]
Looks good.  You tricked me swapping a ````!=```` for an ````==```` but I figured it out on the second pass.  Works for me, thanks for cleaning all of that up!

**Pull request merged**
