### PR TITLE
WIP: Build release within CI

### PR DESCRIPTION
**Pull request by AndreasBilke**

### CODE REVIEW

**Comment by AndreasBilke** [comment]
@fnevgeny I prepared some CI to get rid of the manual release process. (There are some debug things in the yml file to play around with the action without pushing it to master).

The following works (or is prepared)

- Run release job manually (with user input on which tag we want to release)
- Build the demo/video slides, share these artifacts between jobs
- Publish a release (with artifacts attached) based on a tag (not tested, since I am afraid I will destroy something) :)

Missing is:

- replace the version in pdfpc.vala (for `--version` call)
- update CONTRIBUTOR file

Both if these steps results in new commit and I am not sure how to make that smoothly.

There is another issue I don't have a solution so far. Currently I push a signed tag to github which is *the* release and it contains all things for other package maintainers (like debian) to make a release. With the current approach I push a tag, then let the github CI run (which creates new commits) and THAT is the actual release. This approach violates the system of *a tag is the release*.

Maybe we could change the process as follows:

- We decide that some commit should be a new release.
- We let the CI modify pdfpc.vala/CONTRIBUTOR file, push that to a new release branch
- We let the CI create a tag for it (which isn't signed anymore)
- We let the CI create the demo/video assets, publish a release (based on the previously created tag)

Do you have some ideas about the further steps?

**Comment by fnevgeny** [comment]
> * update CONTRIBUTOR file

The content can be replaced with something like "See <https://github.com/pdfpc/pdfpc/graphs/contributors>"

**Comment by fnevgeny** [comment]
> * replace the version in pdfpc.vala (for `--version` call)

First of all, I suggest moving the release-specific code (the version string and the copyright dates) into a separate file.

Then either:

1. *Any* push to that file would trigger a release (with the automatic tagging as you suggested etc), or
2. Like above, but testing for the presence of "pre" in the version string. Once absent, it will trigger a release (and maybe automatically commit another update with the version incremented and "pre" appended, thus beginning a new development cycle).

Alternatively, we continue updating the version string manually, but the CI should assert that the release tag and the version string are equal (and the copyright date = the current year).

What do you think?

**Comment by fnevgeny** [comment]
> I read through https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows and didn't found a way to run a workflow on file change.

E.g., see https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#example-including-paths

> The new approach based on your ideas would be:
> 
>     1. We update pdfpc.vala manually

Or perhaps a smaller one (to be created, e.g., release.vala) containing only the release-specific data.

>     2. We switch to https://github.com/pdfpc/pdfpc/graphs/contributors instead of CONTRIBUTORS file.

Alternatively, the file can be preserved, but the contents will be a short sentence pointing to the guthub URL. This would keep the "-v" output compact.

>     3. We trigger the workflow manually with the following user input:
>        
>        * a commit id (thats our new release) and
>        * the release name (e.g. v4.6.1).

If the release name can be extracted from the sources (pdfpc.vala or release.vala), do we need to specify it explicitly?

>     4. The workflow double check if the proposed release name is found within pdfpc.vala (to avoid publishing a release with wrong version strings) and check for the current year.
> 
>     5. We auto-tag that commit, create a release, attach assets

To avoid the double check in item 4, maybe the automatically prepared release should be made in the  "draft" state, to be verified by the human QA :).

**Comment by AndreasBilke** [comment]
@fnevgeny I pushed all the needed changes for automate the release process. Please have a careful look.

I tried the release also with fake releases (and deleted them afterwards).

To fully activate the whole thing, some small changes to the workflow file must be made (listen for master branch, make releases non-draft).

**Review by fnevgeny — DISMISSED** [review]

**Comment by AndreasBilke** [comment]
Sorry for double reviewing. I made the activation changes which needs another review. If you are fine, please merge this PR.

**Review by fnevgeny — APPROVED** [review]

**Pull request merged**
