### PR TITLE
Display beamer notes at the side instead of next slide

### PR DESCRIPTION
**Pull request by memeplex**
This is just https://github.com/pdfpc/pdfpc/pull/444 rebased in a different branch because of a reorganization of my fork. Sorry for any inconvenience.

### CODE REVIEW

**Comment by AndreasBilke** [comment]
Have you considered my suggestions from https://github.com/pdfpc/pdfpc/pull/444#issuecomment-515488445 ?

**Comment by fnevgeny** [comment]
@memeplex Can you please tell whether #471 would satisfy your needs instead of the native beamer "notes"?

**Comment by memeplex** [comment]
I've been quite busy but will address @AndreasBilke comments as soon as possible (which might not be too soon...). Regarding @fnevgeny alternative, there are technical details that I don't have the time to carefully assess now, but any solution that addresses my use case will be fine.

**Comment by fnevgeny** [comment]
If the beamer notes are to stay at all (#472), the development will likely go as outlined in #479. Hence, closing this PR. Thanks for contributing.

**Pull request closed without merging**
