### PR TITLE
Add files from submodule directly into our repository

### PR DESCRIPTION
**Pull request by AndreasBilke**
Please try this at home! It seems a little bit tricky to delete a submodule. Maybe
```
git submodule deinit
```

must be done before this branch is merged in a working copy (no fresh clone).

### CODE REVIEW

**Comment by AndreasBilke** [comment]
Even with #58 resolved, it is worth to copy the files in our repo directly, since we would not suffer the release tarball problematic as mentioned in #58.

**Comment by rschroll** [comment]
Yeah, the tarball issue is enough to push me over the edge on this one. 
 Including the vala cmake files is the way to go.

In order to move to this branch, I had to run `git submodule deinit .`. 
 Then if I wanted to move back to master, I had to run `git submodule 
init; git submodule update`.  This bothers me for two reasons.  First, 
people casually following our repository will suddenly have their build 
break when we land this in master.  Second, bisecting across this 
boundary will become very annoying very quickly.

I wonder if we could avoid these problems by putting the in-tree 
version of the cmake files into another directory (cmake/vala, 
perhaps).  This would cause existing users to carry two copies of the 
cmake module around, but that's not such a big deal if it solves both 
of those issues above.  Is it worth giving it a try?

**Comment by AndreasBilke** [comment]
I tested leaving the submodule in its place and copy the files to a new location. in @d7abe0e5d2215a906929fb3032cd79cc10f65d22 is the related commit.

But I think this does not do any better, since this would leave the user repo in some strange state where git has submodule references but git does not know about this (no .gitmodules file).

We could leave the .gitmodules file as it is and copy the files to a new location, but than we have a submodule (which we do not use) and the new files.

I do not see a smooth possibility to remove the submodule for existing clones. I think there is always a user intervention neeeded.

In my opinion this pull request here is the better one, since a user get some feedback if he pulles the changes. He has do deinit the submodule first and pull afterwards. This would lead to a clean repo state.

Maybe we should add a note to the README what to do?

**Comment by rschroll** [comment]
According to the git docs for submodule deinit,
> If you really want to remove a submodule from the repository and 
> commit that use git-rm[1] instead.

I've done that, combined with your commit for recreating the files in 
another directory.  See my submodule3 branch.  It seems to work, but 
I'm not sure that it will delete the files in the submodule.  This 
happened when I created that commit, since that's what git rm does.  
But moving back and forth across that commit since, I instead get a 
warning that git can't delete the directory.  (Although this is handy 
in way, since I don't have to do a submodule init; submodule update 
every time I go back before this commit.)

Even if this doesn't delete the old files, I think it's the way to go.  
A simple 'rm -r' will clear out the old directory, which is only 
wasting 32kB, anyway.

With this branch, I worry about how to inform people the need to do a 
submodule deinit first.  A message in the README or commit message 
won't work, because they don't get that until they've solved the merge. 
 Moreover, git recommends removing the submodule files by hand.  This 
works, but the leads to problems when you try to checkout a commit 
prior to the change.

Let me know your thoughts.

**Comment by AndreasBilke** [comment]
In your submodule3 branch, you delete the .gitmodules file and copy the
content to a new directory. Than the user should do by it self a
`git rm cmake/Vala_CMake` ? Do I understand this correctly?

If I do, I would accept submodule3. We get rid of the submodule for new
clones and existing repos can be cleaned in some way.

**Comment by rschroll** [comment]
My commit includes to the `git rm cmake/Vala_CMake` command.  What 
appears to happen is that the git repository includes a special file at 
that location with details on the submodule.  When I ran the command, 
it removed that special file from my repository, the relevant lines 
from the .gitmodules file, and all the files from the submodule 
directory in my working directory.  The first two should happen when 
you pull my change.  I don't think the last one will, so you'll be left 
with untracked files in the working directory.  Those you can remove 
with a standard `rm` command.

I think.  I don't really understand git submodules.

**Comment by AndreasBilke** [comment]
I did a test merge with your branch to verify the behavior. It did removed
the submodule references in the working directory but left the files at its
place (that should happen, right?).

Than I can delete the files on my own with `rm`.

Lets do it this way. Would you like to create a pull request for your
branch?

PS: Actually, I am not satisfied with submodule deletion in git :).

**Pull request closed without merging**
