### PR TITLE
Switch to GStreamer 1.0

### PR DESCRIPTION
**Pull request by rschroll**
Here's the branch discussed in #4, rebased onto the current master.

It has problems when the aspect ratio of the movie doesn't match the aspect ratio of the element it's associated with.  But few people will make presentations like that.  I think it's better to get this in now and open another bug about the aspect ratio issue.

### CODE REVIEW

**Comment by AndreasBilke** [comment]
I did some quick testing with two files. One original mpeg-4 file and one (from the original) webvm/vp8 video. With the webm video I got a segfault when stopping the video or when it ended. No problems with mpeg-4.

However I would push this to master. If there are more specific issues than my quick test we could open bug reports for this.

**Comment by AndreasBilke** [comment]
Is there a chance to include this https://github.com/davvil/pdfpc/pull/79 also in the pull request or should this be a second one?

**Comment by rschroll** [comment]
Can you share the problematic webm video?  Or get a stacktrace?  I'd 
rather not commit code that seg faults if I can help it.  But the 
problem could be inside gstreamer.

davvil#79 should be another pull request.  Actually, it should be 
several, since there seem to be a few different ideas in there.

**Comment by AndreasBilke** [comment]
At https://pub.bilke.org/2015-05-19-BK9gEIcTy1c/ you can see an example.
See crashlog for a backtrace.

It seems, that it only crashes if I use a second monitor (so presenter and
presentation are on different screens) or use the windowed mode. So maybe
the problem lies in the presentation window?

My inital test was done with a converted video my mediagoblin. It didn't
found a quick command line way to convert to webm so I used this workaround
:).

**Comment by AndreasBilke** [comment]
I made a second test, this time using ffmpeg directly.
```ffmpeg -i test.mp4 -c:v libvpx -qmax 25 -c:a libvorbis test.webm```
This webm (same codecs as the crashing video) are working with pdfpc. So maybe my crashing video is not worth the headaches.

I suggest pushing this to master.

**Pull request merged**
