### PR TITLE
Give the list of possible windowed modes in error message

### PR DESCRIPTION
**Pull request by symphorien**
I had to look in the source code to find valid values :(

### CODE REVIEW

**Comment by fnevgeny** [comment]
> I had to look in the source code to find valid values :(

You might read the man page as well :)

**Comment by symphorien** [comment]
oh oops :)

**Comment by AndreasBilke** [comment]
Giving the possible options in the error messages is uncommon at pdfpc. I would prefer (if the man page is not enough) to put it here https://github.com/pdfpc/pdfpc/blob/54a5812bcc5fc92a5c81ef54c197e7d0960c7009/src/pdfpc.vala#L115

**Comment by fnevgeny** [comment]
> Giving the possible options in the error messages is uncommon at pdfpc. I would prefer (if the man page is not enough) to put it here
> 
> https://github.com/pdfpc/pdfpc/blob/54a5812bcc5fc92a5c81ef54c197e7d0960c7009/src/pdfpc.vala#L115

Putting a long description would make the help output exceed the 80-char limit and look untidy as a whole. Maybe we can append the "Read the man page" string to each error message? :)

**Comment by AndreasBilke** [comment]
> Putting a long description would make the help output exceed the 80-char limit and look untidy as a whole. Maybe we can append the "Read the man page" string to each error message? :)

Sure :) We have for some options the possible values directly in the help output, maybe we can make that more consistent.

**Pull request closed without merging**
