### PR TITLE
Get rid of the unused largest_rect

### PR DESCRIPTION
**Pull request by fnevgeny**
Any idea what it was supposed to be used for?

### CODE REVIEW

**Comment by AndreasBilke** [comment]
@fnevgeny yes :) we had the problem of poor video quality on the presentation screen if the presenter screen had a lower resolution compared to the presentation screen.

For whatever reason gstreamer rendered with our former pipeline construction the video on the lowest resolution if both differed. If we force the rendering to the larger resolution everything is fine.

**Comment by fnevgeny** [comment]
OK, I see. But now it's unused, so I think we can safely remove it.

**Comment by AndreasBilke** [comment]
If there is no regression bug then yes

Am 11. Jänner 2019 11:37:22 MEZ schrieb Evgeny Stambulchik <notifications@github.com>:
>OK, I see. But now it's unused, so I think we can safely remove it.

**Comment by fnevgeny** [comment]
> If there is no regression

There could be no regression - the last argument is not used in the function...

**Comment by AndreasBilke** [comment]
> > If there is no regression
> 
> There could be no regression - the last argument is not used in the function...

No, I meant if the regression was already introduced with the pipeling rewriting. But I checked it, everything is fine.

**Pull request merged**
