### PR TITLE
Fullscreen in Wayland sessions.

### PR DESCRIPTION
**Pull request by AndreasBilke**
This should solve #178 . I only could test this within a virtual machine with fedora 25 workstation. I could just test this with single head setup. So please test this carefully.

### CODE REVIEW

**Comment by diraimondo** [comment]
I've tested your PR on the same setup I reported here (https://github.com/pdfpc/pdfpc/issues/149#issuecomment-270455730): the windows placement(size is still wrong for me in the single and dual-head test.

**Comment by AndreasBilke** [comment]
Could you please tell me your environment? (distribution, window manager
etc)?

**Comment by diraimondo** [comment]
@AndreasBilke I'm using Arch Linux and Gnome Shell 3.22.2 over Wayland.

Dual head setup (external screen is the main one):
```
Screen 0: minimum 320 x 200, current 3840 x 3960, maximum 8192 x 8192
XWAYLAND1 connected 3200x1800+364+2160 290mm x 170mm
   3200x1800     59.96*+
XWAYLAND2 connected 3840x2160+0+0 600mm x 340mm
   3840x2160     59.98*+
```

Single head setup (only internal display):
```
Screen 0: minimum 320 x 200, current 3200 x 1800, maximum 8192 x 8192
XWAYLAND1 connected 3200x1800+0+0 290mm x 170mm
   3200x1800     59.96*+
```

Single head setup (only external display):
```
Screen 0: minimum 320 x 200, current 3840 x 2160, maximum 8192 x 8192
XWAYLAND4 connected 3840x2160+0+0 600mm x 340mm
   3840x2160     59.98*+
```

The presentation looks wrong in all of them.

**Comment by AndreasBilke** [comment]
With wrong you mean blurred or the "displacement" problem where the windows
are not really in fullscreen?

**Comment by diraimondo** [comment]
It's not a blur problem: the size and placements are wrong. The main image is bigger then the screen and on the other screen I can see the bottom part of the main image.
Two notes:
- my internal display (configured as second monitor) is logically stacked below the main screen (the external display);
- it looks that pdfpc does ignore that I set my external display as main screen (but this could be another report...).

**Pull request closed without merging**
