### PR TITLE
Fix icon scaling issue for wayland sessions. #321

### PR DESCRIPTION
**Pull request by AndreasBilke**

### CODE REVIEW

**Comment by fnevgeny** [comment]
Why do we need this `1.06` multiplier, BTW?

**Comment by AndreasBilke** [comment]
> Why do we need this `1.06` multiplier, BTW?

I have no clue. It's there since ever :)

**Comment by AndreasBilke** [comment]
I removed the scaling factor.

**Comment by fnevgeny** [comment]
> I have no clue. It's there since ever :)

I think it has no impact anyway. Try putting there 2 or whatever...

**Pull request merged**
