### PR TITLE
Allow font size in/decreasing for notes view

### PR DESCRIPTION
**Pull request by AndreasBilke**
According to issue #32 the font size of the notes view should be
configurable. Keybindings for in/decreasing are added.

### CODE REVIEW

**Comment by rschroll** [comment]
When I tested this, I could only make the font size decrease.  I think the problem is that, to get the "plus" key, I have to press "Shift+equal".  The key_press handler is getting the right keycode, but I expect the additional shift modifier is confusing it.  The easiest thing to do would be to to add a handler for "equal" to also increase the font size.

The + and - keys on my numpad didn't work for changing the font size.  These produce "KP_Add" and "KP_Subtract" events, respectively.

Should the font setting be per presentation or per slide?  I see arguments both ways -- If you're trying to make the font large enough to read, you want that to happen for all the slides.  But if you're reducing the font size so you can view all of your notes for a particular slide, you'd prefer a per-slide setting.  Not sure; just tossing this idea out there.

It seems to me that we ought to save the font size setting (whether per slide or per presentation) in the .pdfpc file.  But maybe that's another bug.

**Comment by AndreasBilke** [comment]
I use a german laptop keyboard and maybe this is the issue? I don't know.
```xev``` gives me this

```
KeyPress event, serial 33, synthetic NO, window 0x1a00001,
    root 0xfa, subw 0x0, time 9156401, (683,673), root:(684,674),
    state 0x0, keycode 35 (keysym 0x2b, plus), same_screen YES,
    XLookupString gives 1 bytes: (2b) "+"
    XmbLookupString gives 1 bytes: (2b) "+"
    XFilterEvent returns: False

KeyPress event, serial 33, synthetic NO, window 0x1a00001,
    root 0xfa, subw 0x0, time 9157201, (683,673), root:(684,674),
    state 0x0, keycode 61 (keysym 0x2d, minus), same_screen YES,
    XLookupString gives 1 bytes: (2d) "-"
    XmbLookupString gives 1 bytes: (2d) "-"
    XFilterEvent returns: False
```

I am open to any other key-combo. The global and per slide in/decrease
functions sounds like a good idea! I will think about it.

**Comment by rschroll** [comment]
We can have multiple keys bound to the same event.  I would recommend 
binding "plus", "equal", and "KP_Add" to the increase font size event, 
for example.

I don't know that we want to have both a per-presentation and per-slide 
font size setting.  Getting the interaction between to two to work 
sensibly would be somewhere between difficult and impossible.  One 
thing we might consider is a system where the user sets the maximum 
font size for a presentation, but the font is automatically reduced to 
fit long notes on screen.  But this may be a separate issue.

It occurs to me that the communication between the controller and the 
controllables could be done with signals, rather than through an 
interface method.  But the interface method is what we use for a bunch 
of other things, so feel free to stick with it.  Someday maybe I'll go 
through all of them and replace them with signals.

**Comment by AndreasBilke** [comment]
I don't think that global and per slide settings are difficult. Lets say you changed the font size globally than the per slide setting would override it.

If a user thinks the the font is in general to small he uses global settings and fine adjustment can be done on per slide basis (e. g. when there is a lot of text).

Another approach might be to specify the global font size in an external CSS which is loaded during start and the fine tuning could be done on per slide basis.

I am open to everything since I have no strong feelings about this feature. I don't use it at all, but it was a user request.

**Comment by AndreasBilke** [comment]
I rebased this branch to master and added more key bindings for in/decreasing. Does this global font changing work now?

**Comment by AndreasBilke** [comment]
I added the possibility to make the font size changes slide specific. Does someone want to try this?

**Comment by rschroll** [comment]
The keybindings seem to work for me.  I can increase and decrease the 
font sizes just fine.


However, the interactions between the per-slide and the global sizes 
are weird.  Suppose I increase the local font size quite a bit for only 
slide X.  Its font increases; all the others stay small.  But now if I 
decrease the global font size by one step on slide X, all of the other 
font sizes jump up to be that same size.  Decreasing the global font 
size has increased the font size for most slides.

Now, decrease the global font size back to where it started.  The slide 
X has the original font size.  Change to another slide, which also has 
the original font size.  Change back to slide X.  Its font is big again!

Increase the global font size again and then quit pdfpc.  Restart it.  
Slide X has a large font, but none of the other slides do.  To make any 
sense of this behavior, the user has to know which slides have had 
their font size set and which are respecting the global size, but 
there's no indication of which is which.  And even if you do keep this 
straight, some of these behaviors are rather surprising.

I wonder if the local font size shouldn't be an absolute size, but 
should be a scale relative to the global size.  This would mean that 
adjusting either the local or global size should always produce 
sensible and consistent results.  I also suspect we may want to save 
the global font size as well.

Even with this change, I'm still worried that this could be confusing.  
Suppose a user makes a local font change and then decides to undo it.  
By mistake, they adjust the global font size to get it back to where it 
started.  They switch to the next slide and discover that font is 
wrong.  If they realize what happened, they adjust the global font, 
switch to the previous slide, adjust the local font, and get on with 
things.  If they don't realize what went wrong, they may adjust the 
local font on the second slide, go to a third, and become even more 
confused.

**Comment by AndreasBilke** [comment]
> Increase the global font size again and then quit pdfpc.  Restart it.  
> Slide X has a large font, but none of the other slides do.

Yes, the global font size should be saved in the per-pdf config file. I
didn't had the time so far for doing this, since this would require more
coding on the configFileReader (config file parsing is currently a total
mess, I think there should be some rewrite).

> I wonder if the local font size shouldn't be an absolute size, but 
> should be a scale relative to the global size.

Nice idea, this sounds more useful.

> Even with this change, I'm still worried that this could be confusing.  
> Suppose a user makes a local font change and then decides to undo it.  
> By mistake, they adjust the global font size to get it back to where it 
> started.  They switch to the next slide and discover that font is 
> wrong.

Do you think this is an issue of the global/local font size feature or just
some keybinding problem? I agree that it a user can easily get confused
with them.

**Comment by rschroll** [comment]
On Sun, Jun 14, 2015 at 6:48 AM, Andreas Bilke 
<notifications@github.com> wrote:
> Do you think this is an issue of the global/local font size feature 
> or just
> some keybinding problem? I agree that it a user can easily get 
> confused
> with them.

I think it's a problem with the model.  There are two commands that 
produce the same immediate effect but have different implications.

A few ideas to consider:
- If a slide has a custom font size, make all the keybindings adjust 
the custom size instead of the global size.
- Have a key command to undo the local size and have the slide use the 
global size.
- Have some visible indicator that a slide is using a custom font size.

But let's back up a bit.  Why would a user want to adjust the font size 
for a specific slide, rather than for all of them?  I can think of two 
reasons offhand:
1) To decrease the font size to fit a long note on the screen without 
scrolling.
2) To make a particularly important note stand out.

I think (1) may be a common use case, but note that the user there 
doesn't actually want to be adjusting the font size -- they just want 
it all to fit.  Maybe we should attack that problem head on.  Two ideas 
come time mind: (a) Automatically decrease the font size from the 
default when we notice that the notes view has a scrollbar.  It might 
be a little tricky to get this working smoothly, but it should be 
possible.  (b) Increase the size of the notes widget when there's a 
large note, decreasing the size the next slide preview.

I'm less convinced that (2) is actually much of an issue.  If a point 
is important, it's probably on the slide, and it's probably big.  But 
note again that the user doesn't want to adjust the font size -- 
they're just using that for lack of a better tool.  If we think this is 
an issue, perhaps we should let the notes contain markdown (or 
similar), so the user can make the relevant text big or bold or red or 
whatever.

If I'm missing use cases for this feature, please point them out.  But 
right now, my recommendation is to get the global font size setting 
working and drop of the local font size.  Then we can attack (1) and/or 
(2) directly.

**Comment by AndreasBilke** [comment]
> If I'm missing use cases for this feature, please point them out.  But 
> right now, my recommendation is to get the global font size setting 
> working and drop of the local font size.  Then we can attack (1) and/or 
> (2) directly.

Would you say the global font size feature is complete except from the
"save to config file" possibility?

**Comment by AndreasBilke** [comment]
The font size is now saved in the pdfpc file.

**Comment by AndreasBilke** [comment]
Could someone else test this feature? Does it work at all, is the behaviour consistent?

**Comment by miguelgraz** [comment]
Hello @AndreasBilke and @rschroll!

So I'm in love with this project and would love to have this feature, I just cloned https://github.com/AndreasBilke/pdfpc, checked out to `issue-32` branch, compiled and tested and it seems to work fine, increasing and decreasing the font size globally using minus-key and plus/equal-key, without the need to use control or shift keys.

For some reason (and I really don't know if that related to this change or some other) it seemed to not being full-screen as the release on the repository, here's a screenshot:
ss1

For the record, I'm running Ubuntu 15.03 on a Samsung AtivBook 9, for this test I didn't have any external monitor unfortunately.

Thank you!

**Comment by miguelgraz** [comment]
Also not sure if this changes anything but I'm having this weird "window" behavior even for really small font-sizes and for PDFs without any notes, so it's probably unrelated to this PR specifically.

Seems to work great! :shipit: 

Thanks!

**Comment by farseerfc** [comment]
Hi, thank you for this work!

I tested on my laptop but unfortunately, I can only decrease the font size but not increase it (easily).

I suspect the reason is that I am using a Japanese layout, and the two increase key (=+) requires pressing shift (= is above -, and + is above ;) .
Could you add more keys, I think [] keys are good choice on my Japanese layout keyboard.

Thanks in advance!

**Comment by AndreasBilke** [comment]
> For some reason (and I really don't know if that related to this change or some other) it seemed to not being full-screen as the release on the repository, here's a screenshot:

This problem might be related to #68 and #64 but we have currently no
progress in this. I can't reproduce that problem on my machine and I didn't
had the time to setup some test VM with the setup like these two issues
(both use ubuntu).

**Comment by AndreasBilke** [comment]
It is possible to have a local pdfpcrc to specify some own key bindings.
But if you like, you can send me the corresponding key codes and I will
test and add them to the default config.

**Comment by farseerfc** [comment]
Thank you! This is what I got from `xev` for `[]-+` keys on my Japanese layout:

```
KeyPress event, serial 33, synthetic NO, window 0x5600004,
    root 0xa58, subw 0x0, time 2250052006, (869,212), root:(877,245),
    state 0x0, keycode 35 (keysym 0x5b, bracketleft), same_screen YES,
    XLookupString gives 1 bytes: (5b) "["
    XmbLookupString gives 1 bytes: (5b) "["
    XFilterEvent returns: False

KeyPress event, serial 36, synthetic NO, window 0x5600004,
    root 0xa58, subw 0x0, time 2250053190, (869,212), root:(877,245),
    state 0x0, keycode 51 (keysym 0x5d, bracketright), same_screen YES,
    XLookupString gives 1 bytes: (5d) "]"
    XmbLookupString gives 1 bytes: (5d) "]"
    XFilterEvent returns: False

KeyPress event, serial 36, synthetic NO, window 0x5600004,
    root 0xa58, subw 0x0, time 2250064623, (869,212), root:(877,245),
    state 0x0, keycode 20 (keysym 0x2d, minus), same_screen YES,
    XLookupString gives 1 bytes: (2d) "-"
    XmbLookupString gives 1 bytes: (2d) "-"
    XFilterEvent returns: False

KeyPress event, serial 36, synthetic NO, window 0x5600004,
    root 0xa58, subw 0x0, time 2250065415, (869,212), root:(877,245),
    state 0x1, keycode 47 (keysym 0x2b, plus), same_screen YES,
    XLookupString gives 1 bytes: (2b) "+"
    XmbLookupString gives 1 bytes: (2b) "+"
    XFilterEvent returns: False
```

**Comment by AndreasBilke** [comment]
@farseerfc could you test the new bindings? If its okay could someone do the last testing before I merge this into master? Maybe @rschroll can help :).

**Comment by farseerfc** [comment]
@AndreasBilke Thanks, I have tested the new binding and they are working fine!

**Pull request merged**
