### PR TITLE
Window size

### PR DESCRIPTION
**Pull request by andybarry**
(Moving this over to the new pdfpc repo)

I wanted to use pdfpc in a kiosk mode for an interactive presentation where I would also have videos playing on the screen. To do this, I needed to force a particular size for the windowed mode so I could have the presentation on one side and my videos on the other. This pull request implements a size option (in pixels) for the width and height of the window (forces windowed mode).

### CODE REVIEW

**Comment by rschroll** [comment]
The actual content of this looks fine to me!

I've made a few style comments.  I realize this was written before we 
decided on the Yorba style (have we, in fact?), but I'd prefer to set 
out the right way, style-wise.

My preference would be to put all of the whitespace corrections in a 
single commit before any of the other fixes. Of course, this is the 
sort of thing that only makes sense to do if we're going with a logical 
history, not actual history, and I don't think we've made a decision on 
that subject.

Once you fix the style and rebase the whitespace issues (if we decide 
to go that way), I think it's ready to be merged!

**Comment by andybarry** [comment]
OK I think I've done the right thing with the rebase.  That's my first time with this workflow, so appologies if it's messed up.  This commit is based off of my whitespace fix, which is why the diff is so big.  I think that when we merge the whitespace fix in, git/github with automatically figure it out and the diff will shrink.

I addressed your comments as well.  Take a look and tell me what you think.

**Comment by rschroll** [comment]
I didn't know you could rewrite a pull request in progress.  Did you 
just do a rebase and then a push -f?

Anyway, once you push the whitespace fix and rebase on top of that, I 
think you can go ahead and push this too.

**Comment by andybarry** [comment]
Any changes to the branch that the pull request is on automatically change the pull request.

I did indeed rebase and push -f.  It didn't seem like the perfect workflow, but it did get the job done.  Will be better once I rebase before pull requesting.

I have now merged in the whitespace fixes and it looks good.  Messing with the git history is definitely odd, but I think I'll probably get the hang of it moving forward.

**Pull request merged**
