### PR TITLE
Escape square brackets in text notes.

### LINKED ISSUE #200: Square Brackets in Notes lead to deletion in pdfpc-file when closing pdfpc
When writing some notes in the presenter console I made the mistake to insert a word with square brackets: [word-in-brackets]
After closing pdfpc with the q command and reopening it, all notes after this entry including the [word-in-brackets] were gone, deleted from the .pdfpc file.

I now understand (after the fact) that this might be covered by the manual saying that the note section must be the last one in the file, but it would have saved me two hours of work if the manual had explicitly stated that using square brackets in the notes will violate this requirement and lead to unwanted consequences (in my case: deletion)

*Suggestion:* Put a note in the manual saying that using square brackets in the notes is not a good idea.

### PR DESCRIPTION
**Pull request by AndreasBilke**
This should fix #200

### CODE REVIEW

**Comment by AndreasBilke** [comment]
Thank you for noticing the `#` as well. I use now GLib.Regex for this, since it is quite elegant to have a single call for replace. I did not added the `\` because we do not use it for special purposes.

I thought of dumping the raw file content to stderr if we mess something up when parsing the file. Then the user would have the chance to save his work instead of loosing everything as noted in the initial issue. What do you think about it?

**Comment by phillipberndt** [comment]
How about going one step further and *aborting* in this case? Sure, it'd stop pdfpc from working, but it would also preserve the original notes file instead of overwriting it. The error message could include a hint to the notes file and the user's option to remove it.

**Comment by AndreasBilke** [comment]
Aborting for parsing the file seems better. But what about "strange" user input which can't be written to the file?

**Comment by phillipberndt** [comment]
That would lead to an error when *writing* the file rather than upon *reading* it, wouldn't it? In that case, printing the notes to stdout seems to be a good option, right.

**Pull request merged**
