### PR TITLE
Dbus actions with arguments

### PR DESCRIPTION
**Pull request by fnevgeny**
This implements support for invoking through DBus an action that requires an argument (e.g., switchMode) and adds one more such an action (gotoPage).

### CODE REVIEW

**Comment by AndreasBilke** [comment]
Hm, I have no dbus, so I can't test anything.

**Comment by fnevgeny** [comment]
> Hm, I have no dbus, so I can't test anything.

How is that? Do you get an error message each time from pdfpc trying to deactivate screensaver via dbus?

**Comment by AndreasBilke** [comment]
I'm using FreeBSD :). I get no message, because in that case a message is not logged.

**Comment by fnevgeny** [comment]
> I'm using FreeBSD :).

Ah right. But a port surely exists <https://www.freebsd.org/cgi/man.cgi?query=dbus-daemon>...

**Comment by AndreasBilke** [comment]
Yes, but I don't want to have it :)

Am 9. April 2019 12:40:41 MESZ schrieb Evgeny Stambulchik <notifications@github.com>:
>> I'm using FreeBSD :).
>
>Ah right. But a port surely exists
><https://www.freebsd.org/cgi/man.cgi?query=dbus-daemon>...

**Pull request merged**
