### PR TITLE
Create a separate window for glimagesink instances (See #240)

### PR DESCRIPTION
**Pull request by AndreasBilke**

### CODE REVIEW

**Comment by phillipberndt** [comment]
I have just pushed a second commit that partially reverts #228: With it, pdfpc would again by default choose the xvimagesink and don't use the code to create separate windows. To use the glimagesink and associated code paths, `option gstreamer-pipeline glimagesink` has to be added pdfpcrc. 

Related to #197, #240, #253.

**Comment by severin-lemaignan** [comment]
If I'm right, this means that the default behaviour of `pdfpc` on `gnome-shell` (or any other composer using client-side decorations) is to *not* display videos (ie #197)... even though this can be changed with the appropriate flag, it makes for a poor first experience for many users... What prevents creating a 2nd window for opengl rendering to be the default?

**Comment by AndreasBilke** [comment]
@severin-lemaignan that multiple people have problems with this behaviour. And I think a crashing pdfpc is worse than a non-working video.

**Comment by phillipberndt** [comment]
The error in #197 is not generic to such environments, there must be something else in play. I am not affected, though to my best knowledge my pdfpc windows should have ARGB visuals, too, and I also have an Intel video card in my notebook. I agree that the present solution is not ideal, but fixing bugs by introducing regressions for other users is a no-go for me. If you can come up with a reliable way of detecting which pipeline to use, I'd be all for adding a third option, "autodetect", and make that one the default choice.

**Comment by severin-lemaignan** [comment]
@AndreasBilke crashing pdfpc is definitely worst, I agree. I've only seen the issue #253 caused by the creation of a secondary window -- could you link as well to the other reported regressions?
@phillipberndt ok, I didn't know you were in the same situation without experiencing the issue. You might want to mention that on #197.

**Comment by phillipberndt** [comment]
@severin-lemaignan See #253 for a regression & for another example of a gnome user for which xv works as expected.

**Comment by severin-lemaignan** [comment]
Well, then I guess I'm back digging into this issue again... deeper and deeper... :-)

**Pull request merged**
